from __future__ import annotations

import ast
from dataclasses import dataclass
from pathlib import Path

from src.tools.repo_scanner import RepositoryScanResult


@dataclass(frozen=True)
class FunctionSummary:
    module_name: str
    function_name: str
    arg_count: int


@dataclass(frozen=True)
class GeneratedTestSuite:
    test_file_name: str
    content: str
    covered_functions: list[str]

    @property
    def test_count(self) -> int:
        return len(self.covered_functions)


FORBIDDEN_GENERATED_IMPORTS = {
    "os",
    "pathlib",
    "requests",
    "shutil",
    "socket",
    "subprocess",
    "sys",
    "urllib",
}


def generate_pytest_tests(
    project_path: str | Path,
    scan: RepositoryScanResult,
    max_functions: int = 8,
) -> GeneratedTestSuite:
    root = Path(project_path).resolve()
    summaries = _discover_functions(root, scan.source_files)[:max_functions]

    lines = [
        "\"\"\"Generated by TestGuard Agent.\"\"\"",
        "",
        "import pytest",
        "",
    ]
    covered: list[str] = []

    for summary in summaries:
        module_alias = summary.module_name.replace(".", "_")
        import_line = f"import {summary.module_name} as {module_alias}"
        if import_line not in lines:
            lines.append(import_line)

    if summaries:
        lines.append("")

    for summary in summaries:
        module_alias = summary.module_name.replace(".", "_")
        test_name = f"test_{module_alias}_{summary.function_name}"
        test_lines = _generate_test_case(test_name, module_alias, summary.function_name)
        lines.extend(test_lines)
        lines.append("")
        covered.append(f"{summary.module_name}.{summary.function_name}")

    if not summaries:
        lines.extend(
            [
                "def test_testguard_no_public_functions_discovered():",
                "    pytest.skip('No public functions discovered by TestGuard.')",
                "",
            ]
        )

    content = "\n".join(lines).rstrip() + "\n"
    validate_generated_test_code(content)
    return GeneratedTestSuite(
        test_file_name="test_testguard_generated.py",
        content=content,
        covered_functions=covered,
    )


def validate_generated_test_code(content: str) -> None:
    tree = ast.parse(content)
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                root_name = alias.name.split(".", 1)[0]
                if root_name in FORBIDDEN_GENERATED_IMPORTS:
                    raise ValueError(f"Generated tests import forbidden module: {root_name}")
        elif isinstance(node, ast.ImportFrom):
            root_name = (node.module or "").split(".", 1)[0]
            if root_name in FORBIDDEN_GENERATED_IMPORTS:
                raise ValueError(f"Generated tests import forbidden module: {root_name}")


def _discover_functions(root: Path, source_files: list[str]) -> list[FunctionSummary]:
    summaries: list[FunctionSummary] = []
    for relative_file in source_files:
        path = root / relative_file
        if path.name == "__init__.py":
            continue

        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except UnicodeDecodeError:
            tree = ast.parse(path.read_text())

        module_name = _module_name_from_path(relative_file)
        for node in tree.body:
            if not isinstance(node, ast.FunctionDef):
                continue
            if node.name.startswith("_"):
                continue
            summaries.append(
                FunctionSummary(
                    module_name=module_name,
                    function_name=node.name,
                    arg_count=len(node.args.args),
                )
            )
    return summaries


def _module_name_from_path(relative_file: str) -> str:
    path = Path(relative_file)
    return ".".join(path.with_suffix("").parts)


def _generate_test_case(test_name: str, module_alias: str, function_name: str) -> list[str]:
    call = f"{module_alias}.{function_name}"
    lower_name = function_name.lower()

    if lower_name in {"add", "sum_numbers", "sum_values"} or lower_name.startswith("add_"):
        return [
            f"def {test_name}():",
            f"    assert {call}(1, 2) == 3",
        ]
    if lower_name in {"subtract", "sub"} or lower_name.startswith("subtract_"):
        return [
            f"def {test_name}():",
            f"    assert {call}(5, 3) == 2",
        ]
    if lower_name in {"multiply", "mul"} or lower_name.startswith("multiply_"):
        return [
            f"def {test_name}():",
            f"    assert {call}(2, 3) == 6",
        ]
    if lower_name in {"divide", "div"} or lower_name.startswith("divide_"):
        return [
            f"def {test_name}():",
            f"    assert {call}(4, 2) == 2",
            "    with pytest.raises(ZeroDivisionError):",
            f"        {call}(1, 0)",
        ]
    if lower_name.startswith("is_") or lower_name.startswith("has_"):
        return [
            f"def {test_name}():",
            f"    result = {call}('test@example.com')",
            "    assert isinstance(result, bool)",
        ]

    return [
        f"def {test_name}():",
        f"    assert callable({call})",
    ]
