from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from src.agents.security_checker import assert_generated_test_code_is_safe
from src.agents.test_planner import TestPlan, TestPlanItem, plan_tests
from src.tools.repo_scanner import RepositoryScanResult


@dataclass(frozen=True)
class GeneratedTestSuite:
    test_file_name: str
    content: str
    covered_functions: list[str]

    @property
    def test_count(self) -> int:
        return len(self.covered_functions)


def generate_pytest_tests(
    project_path: str | Path,
    scan: RepositoryScanResult,
    max_functions: int = 8,
) -> GeneratedTestSuite:
    plan = plan_tests(project_path, scan, max_functions=max_functions)
    return generate_pytest_tests_from_plan(plan)


def generate_pytest_tests_from_plan(plan: TestPlan) -> GeneratedTestSuite:
    items = plan.items

    lines = [
        "\"\"\"Generated by Software Engineer Agent.\"\"\"",
        "",
        "import pytest",
        "",
    ]
    covered: list[str] = []

    for item in items:
        module_alias = item.module_name.replace(".", "_")
        import_line = f"import {item.module_name} as {module_alias}"
        if import_line not in lines:
            lines.append(import_line)

    if items:
        lines.append("")

    for item in items:
        module_alias = item.module_name.replace(".", "_")
        test_name = f"test_{module_alias}_{item.function_name}"
        test_lines = _generate_test_case(test_name, module_alias, item)
        lines.extend(test_lines)
        lines.append("")
        covered.append(item.qualified_name)

    if not items:
        lines.extend(
            [
                "def test_software_engineer_no_public_functions_discovered():",
                "    pytest.skip('No public functions discovered by Software Engineer Agent.')",
                "",
            ]
        )

    content = "\n".join(lines).rstrip() + "\n"
    validate_generated_test_code(content)
    return GeneratedTestSuite(
        test_file_name="test_software_engineer_generated.py",
        content=content,
        covered_functions=covered,
    )


def validate_generated_test_code(content: str) -> None:
    assert_generated_test_code_is_safe(content)


def _generate_test_case(test_name: str, module_alias: str, item: TestPlanItem) -> list[str]:
    call = f"{module_alias}.{item.function_name}"
    scenario = item.scenario

    if scenario == "numeric addition happy path":
        return [
            f"def {test_name}():",
            f"    assert {call}(1, 2) == 3",
        ]
    if scenario == "numeric subtraction happy path":
        return [
            f"def {test_name}():",
            f"    assert {call}(5, 3) == 2",
        ]
    if scenario == "numeric multiplication happy path":
        return [
            f"def {test_name}():",
            f"    assert {call}(2, 3) == 6",
        ]
    if scenario == "division happy path and zero-division boundary":
        return [
            f"def {test_name}():",
            f"    assert {call}(4, 2) == 2",
            "    with pytest.raises(ZeroDivisionError):",
            f"        {call}(1, 0)",
        ]
    if scenario == "predicate returns boolean":
        return [
            f"def {test_name}():",
            f"    result = {call}('test@example.com')",
            "    assert isinstance(result, bool)",
        ]

    return [
        f"def {test_name}():",
        f"    assert callable({call})",
    ]
